// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnkvllqsonnutlxgcfxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRua3ZsbHFzb25udXRseGdjZnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDA0NDAsImV4cCI6MjA1OTAxNjQ0MH0.Wm4JlkaNBnnQ3Z530buPw50rKtZloS0raG8nYo0ZCT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);